services:
    web:
        build:
          context: ../
          dockerfile: ./docker/Dockerfile
        #volumes:
         # - ../www:/var/www/html
         # - ../docker/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

    pixelflut:
      image: sbernauer/breakwater
      ports:
         - "1234:1234"
         - "5900:5900"
         - "9100:9100"